language: cpp

os:
 - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
 
compiler:
  - gcc
  
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi

script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make VERBOSE=1
