language: cpp

os:
 - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - lcov
 
compiler:
  - gcc
  
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6"; fi
  - export GCOV="gcov-6"

script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make VERBOSE=1
  - ctest --verbose
  - cd ..

after_success:
  - mkdir coverage
  - cd coverage
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=yes ..
  - make
  - ctest
  - lcov --gcov-tool $GCOV --directory . --capture --output-file coverage.info
  - lcov --gcov-tool $GCOV --remove coverage.info '/usr/*' --output-file coverage.info 
  - lcov --gcov-tool $GCOV --remove coverage.info 'googletest' --output-file coverage.info 
  - lcov --gcov-tool $GCOV --remove coverage.info '*.t.cpp' --output-file coverage.info 
  - lcov --gcov-tool $GCOV --list coverage.info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  - cd ..

env:
  global:
  - LANG="en_US.UTF-8"
