language: cpp

os:
 - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - g++-5
    - clang-3.7
 
compiler:
  - gcc
  - clang
  
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
- if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.7"; fi

script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make VERBOSE=1
